### PR TITLE
PBL-21165 Add hiddenApp & onlyShownOnCommunication to settings

### PR DESCRIPTION
**Pull request by cjwilliams**

### CODE REVIEW

**Comment by cjwilliams** [comment]
Note: This allows developers that are using PebbleKit JS (not Pebble.js) to specify onlyShownOnCommunication (selecting "Only Visible When Companion App Running" option), even though that's going to end up with ghost apps if they select incorrectly. I didn't think checking for the presence of JS files in the project at the time of showing the selector was worth pursuing for a rarely-used flag, but I can go back and alter, if we're worried about error-checking developers.

**Comment by unwiredben** [comment]
I wonder if that case should be handled in the build tool so it would catch it for non-CloudPebble users too.  Having that in settings means a lot of consistency checking, since you can add JS files after the project is created.

**Comment by cjwilliams** [comment]
Your suggestions have resulted in a ticket being created for better appinfo.json field checking, yay!

**Comment by cjwilliams** [comment]
@Katharine, code review please!

**Comment by Katharine** [comment]
:+1:

**Pull request merged**
