### PR TITLE
Update qemu-enter-token.html to use "tel" input type, instead of "text"

### PR DESCRIPTION
**Pull request by xoneco**
Allows for much more convenient mobile input of the purely numerical code.

On mobile, the "tel" input type instructs the keyboard to default to numerical input.
With the "text" input type the normal keyboard is displayed. More buttons have to be pressed to be able to input numeric values.

### CODE REVIEW

**Comment by Katharine** [comment]
As I recall, changing the type to `tel` breaks the CSS; some minor additional adjustment would be needed on top of this.

(Additionally, on iOS you *already* get numeric input; it recognises the numeric-only pattern restriction and provides an appropriate keyboard.)

**Comment by xoneco** [comment]
I didn't know it already worked on iOS. Definitely makes sense to adjust the keyboard based on a regex pattern.

I should have probably said "android" instead of "mobile" earlier. Sorry :)

I have made the required minor adjustments in the mobile.css file.

**Comment by Katharine** [comment]
I'd probably be inclined to just add `input[type=tel]` to the main set; there's no reason I'd ever want `tel` fields to look different.

**Comment by xoneco** [comment]
Ok, I have made the changes in common.css.

**Comment by xoneco** [comment]
Is there anything else that needs changing?

**Comment by Katharine** [comment]
Sorry, this should be good to go — I've just been too busy to test and verify. :(

**Pull request merged**
