### PR TITLE
PBL-20878 GitHub import doesn't appear to like ~bw and ~color

### LINKED ISSUE #133: Importing 3.0 projects with ~bw / ~color resources fails
I just tried importing a project that's working well with version 3.0-dp3 of the native SDK into CloudPebble. My project uses [per-platform resources](http://developer.getpebble.com/guides/pebble-apps/resources/image-resources/#specifying-resources-per-platform):

> When packing resources into a Pebble project, the SDK will look for any files with special suffixes and use those in preference to those without. The suffixes `~color` and `~bw` are currently supported. If one of these files is found, it will be used instead of any other matching file name without the suffix for platforms that support those colors.

CloudPebble doesn't seem to support this, as I received the following error when importing:

> Error: "There is no item named u'resources/dial_base.png' in the archive"

It's correct that there is no `resources/dial_base.png`, but there *is* a file called `dial_base~bw.png` in the `resources/` directory that should get picked up for Aplite instead.

My project is currently configured to build only for Aplite, but I also tested an archive that provides `dial-base~color.png` as well so that both platform-specific files exist, which generated the same error message.

### PR DESCRIPTION
**Pull request by Spacerat**
This PR fixes #133 by also checking for ~bw and ~color versions of resources when a non-suffixed version is mentioned in the resource manifest.

Things tested to work:
- Importing, building and running the tea-timer example for colour pebble time
- Making a default pebble.js project on cloudpebble.net and adding a colour+bw resource, pushing it to github, importing it on my local cloudpebble, building and running it.

At the moment, in the unlikely event that a project has bw/color *and* 'default' variants of a file, all three would show up in the editor. This might not be perfect, but it's an improvement on the current state.

### CODE REVIEW

**Comment by Katharine** [comment]
The old "black & white" (which is actually the generic image) should probably be changed to "Generic" or something.

Otherwise, looks okay to me.

**Comment by Spacerat** [comment]
If we do that at the moment, then uploading a BW and colour image to cloudpebble will, at the moment, give you a generic and colour, and cloudpebble can never actually create a ~bw image. I'm guessing what we really want is something like...
- Upload just a B&W image, variant = 0
- Upload B&W and color image, variants = 1, 2
?

**Comment by Katharine** [comment]
No — "generic" and "colour" is pretty reasonable.

**Comment by Spacerat** [comment]
In which case, done

**Pull request merged**
